name: Godot Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Godot version
        run: godot --version

      - name: Import project
        run: godot --headless --editor --path fantasy_rpg --quit

      - name: Run project
        run: godot --headless --path fantasy_rpg --quit-after 10
